"""enum_type

Revision ID: 7d0575ba4608
Revises: 36de70108aeb
Create Date: 2023-07-22 21:54:57.427307

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7d0575ba4608"
down_revision = "36de70108aeb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_session_sessionmodel", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "level",
            existing_type=sa.Enum(
                "LEVEL0", "LEVEL1", "LEVEL2", "LEVEL3", name="sessionlevel"
            ),
            type_=sa.String(length=6),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_session_sessionmodel", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "level",
            existing_type=sa.String(length=6),
            type_=sa.Enum("LEVEL0", "LEVEL1", "LEVEL2", "LEVEL3", name="sessionlevel"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
