"""alter not null

Revision ID: b87a6a07c25d
Revises: 4a6b4ef804a9
Create Date: 2023-09-07 19:51:01.314325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87a6a07c25d'
down_revision = '4a6b4ef804a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_session_sessionmodel', schema=None) as batch_op:
        batch_op.alter_column('id1',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('id2',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('id3',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_session_sessionmodel', schema=None) as batch_op:
        batch_op.alter_column('id3',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('id2',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('id1',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
